[build-system]
requires = ["setuptools>=61.0", "Cython", "numpy", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bonsaiana"
version = "1.0.0"
description = "Python package for analyzing N-body simulation data with Bonsai code"
readme = "README.md"
authors = [
    {name = "Tetsuro Asano"},
]
license = "MIT"
requires-python = ">=3.8"
dependencies = [
    "cython",
    "numpy",
    "wurlitzer",
    "pandas",
]

[project.optional-dependencies]
formats = [
    "h5py",
    "pyarrow",
    "asdf",
]
test = [
    "pytest",
    "notebook",
]

[tool.setuptools]
packages = ["bonsaiana"]

[tool.setuptools.package-data]
bonsaiana = ["*.pxd", "*.pyx"]
