[build-system]
requires = ["setuptools>=61.0", "Cython", "numpy", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bonsaiana"
version = "1.0.0"
authors = [
    {name = "Tetsuro Asano"},
]
requires-python = ">=3.8"
dependencies = [
    "cython",
    "numpy",
    "wurlitzer",
]

[tool.setuptools]
packages = ["bonsaiana"]
